### ISSUE TITLE
Authentication system

### ISSUE THREAD

**Issue by JManders07** [TravelXPToday/Frontend#19]
- [ ]  Role system
- [ ]  Segmentation (example: a non logged in user can not create a journey)

**Comment by Artnooijen** [comment]
- [ ] Both students understand and reviewed the created subject.
- [ ] If necessary the subject is shown to the teacher, else both students aggreed it as done
- [ ] The feedback of the teacher or collaborator student is implemented (Or not if disagree).
- [ ] Has to be documented and integrated into both students Portfolio.
